version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'rockoutfit'
      MYSQL_PASSWORD: 'rockoutfit'
      MYSQL_ROOT_PASSWORD: 'rockoutfit'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: